title: GitHub Pages Skills Course
author: bkusuma
description: A site made for GitHub Pages course
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: StarHPC/jekyll-rtd-theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
